services:
  - type: web
    name: bookmart
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn students.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: students.settings